all:
	
	# tell pony to compile as a library and to output an obj file ".o"
	# Note: when you do this and you include an FFI actor in your pony code, pony will also
	# generate a .h file with the bindings you need.
	/Volumes/Development/Development/pony/ponyc/build/release/ponyc -l -robj
	
	# compile our GLUT c code with the pony runtime lib and the .o generated by pony.
	# compile pony from source to get the runtime lib.
	# you will also want pony.h from the runtime source directory
	gcc glut_main.c pony_glut_example.o libponyrt.a -DGL_SILENCE_DEPRECATION -lobjc -framework GLUT -framework OpenGL
	
	# run out executable
	./a.out